package boLang.test.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int TestSuite = 0;
  public static final int assert_statement = 1;
  public static final int execute_single_test = 2;
  public static final int execute_tests = 3;
  public static final int test_case = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xa09f958a0bb141e7L, 0x809fabcf941b13ebL);
    builder.put(0x175473f5555f802cL, TestSuite);
    builder.put(0x175473f5556778beL, assert_statement);
    builder.put(0x648c1dc380d824f7L, execute_single_test);
    builder.put(0x648c1dc380d6939cL, execute_tests);
    builder.put(0x175473f5555f802fL, test_case);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
